### ISSUE TITLE
Clarify who's organizing the conference

### ISSUE THREAD

**Issue by copumpkin** [cko/nixcon2017#2]
There seems to be a fair amount of confusion on IRC and nobody seems to know who's actually behind the conference. Would be nice to give credit and also have an idea who's putting in the work to make this thing happen!

**Comment by cko** [comment]
We are working on a page.

**Comment by cko** [comment]
not everyone involved in the conference has registered yet, but you will find a list at http://nixcon2017.org/participants.html
